// <auto-generated />
namespace BonTemps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomermodeleditedPhonetostringwithregex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomermodeleditedPhonetostringwithregex));
        
        string IMigrationMetadata.Id
        {
            get { return "201801262111474_Customermodel edited. Phone to string with regex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
