// <auto-generated />
namespace BonTemps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_uniqetablelayout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_uniqetablelayout));
        
        string IMigrationMetadata.Id
        {
            get { return "201801182001432_update_uniqe table layout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
